<a href="https://colab.research.google.com/github/DuplamenteH/Machine-Learning/blob/master/RegressapLogistica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Carregando csv

In [0]:
import pandas as pd
from collections import Counter as count
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import MultinomialNB
import numpy as np
path = '/content/drive/My Drive/DadosAlura/'

In [2]:
avaliacoes = pd.read_csv(path+'avaliacoes_usuario.csv',sep=',',encoding='iso-8859-1' )
avaliacoes.head()

Titulo  Documentary  ...  Investimento  Gostou
0              Nixon (1995)            0  ...      7.930748       1
1  Leaving Las Vegas (1995)            0  ...     18.276555       1
2         Persuasion (1995)            0  ...     16.582232       1
3               Babe (1995)            0  ...     13.004553       1
4         Carrington (1995)            0  ...     14.418120       1

[5 rows x 17 columns]

In [3]:
count(avaliacoes['Gostou'])

Counter({0: 135, 1: 543})

#Separando dados 

In [0]:
features  = avaliacoes[avaliacoes.columns[1:16]]
gostos = avaliacoes[avaliacoes.columns[16:]]

treino, teste, treino_marcacoes, teste_marcacoes = train_test_split(features, gostos)



In [5]:
treino = np.array(treino).reshape(len(treino), 15)
teste = np.array(teste).reshape(len(teste), 15)
type(treino)

numpy.ndarray

In [0]:
treino_marcacoes = treino_marcacoes.values.ravel()
teste_marcacoes = teste_marcacoes.values.ravel()

In [7]:
treino_marcacoes

array([1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,

In [8]:
teste_marcacoes

array([1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0])

In [9]:

type(treino_marcacoes)

numpy.ndarray

In [10]:
type(teste_marcacoes)

numpy.ndarray

#Modelo

movieId,Titulo,Documentary,Sci-Fi,Mystery,Horror,Romance,Thriller,Crime,Fantasy,Comedy,Animation,Children,Drama,Adventure,Duracao,Investimento,Bilheteria
9999999,Zootopia,0,0,0,0,0,0,0,1,1,1,1,0,1,110,27.74456356,?????

In [17]:
#REVISAR O ERRO ABAIXO

modelo = LogisticRegression(max_iter=10000)
modelo.fit(treino,treino_marcacoes)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=10000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
previsoes = modelo.predict(teste)

acuraria = accuracy_score(teste_marcacoes, previsoes)

In [19]:
print(acuraria)

0.7470588235294118


In [0]:
zootopia = [0,0,0,0,0,0,0,1,1,1,1,0,1,110,27.74456356]

In [26]:
zootopiaResult=modelo.predict([zootopia])
print(zootopiaResult)
#Resultado 1 logo ele gostou de zootopia

teste2 = [1,1,1,1,1,1,1,0,1,0,0,0,1,150,37.74456356]
resultTeste2 = modelo.predict([teste2])
print(resultTeste2)

[1]
[0]


#Testando com naive bayes

In [0]:
modelo_NB = MultinomialNB()
modelo_NB.fit(treino, treino_marcacoes)


previsoesNB = modelo_NB.predict(teste)
acurariaNB = accuracy_score(teste_marcacoes, previsoesNB)

In [15]:
print(acurariaNB)

0.7058823529411765


In [27]:
modelo_NB.predict([zootopia])

array([1])

In [28]:
modelo_NB.predict([teste2])

array([0])